abcxyz/github-token-minter

configs/abcxyz/infra.yaml

Lets make this work first, then we can discuss securing options.

infra configs

---

configs/abcxyz/breakglass.yaml
configs/abcxyz/github-token-minter.yaml
configs/abcxyz/infra.yaml
configs/abcxyz/readability.yaml
configs/abcxyz/secure-setup-terraform.yaml
pkg/server/config_store.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

Added ability to match on a * wildcard or via a prefix match
Fixed a few typos in the configuration files

feat: validation for the requested repositories - closes #30

---

.github/actions/mint-token/action.yml

Otherwise minty taints the workspace

Do not export credentials for minty

---

pkg/server/token_minter.go
pkg/server/token_minter_test.go

fix: add audit logging back

---

pkg/config/config.go
pkg/config/config_evaluator.go

Will add a unit test to capture this scenario in a follow up

fix: in repo configuration without requested scope caused org configuration not to be checked

---

pkg/config/config_evaluator_test.go
pkg/server/token_minter.go

Added additional unit test for multi loader evaluation

chore: add additional logging to help with failure diagnosis. 

---

.github/minty.yaml
pkg/config/config.go
pkg/config/config_evaluator.go
pkg/config/config_test.go

Prevent mistakes by providing CEL variable for well known OIDC token issuers.
https://github.com/abcxyz/github-token-minter/issues/134

Add CEL variable for well known issuers

---

pkg/server/claims.go
pkg/server/claims_test.go
pkg/server/token_minter_test.go

Parse email claim from OIDC token, but only when `email_verified` is `true`.

Parse email claim from OIDC token

---

.github/minty.yaml

Allow Google token from WIF Service Account to call minty - prereq for integration test.

MintyCfg - Allow Google token from WIF Service Account for integ scope

---

.github/actions/mint-token/action.yml
.github/workflows/ci.yml

Integration test that calls github-token-minter with a Google-issued OIDC token and verifies that it receives a valid GitHub token in response

Integration test for gcloud token support

---

.github/actions/mint-token/action.yml

Revert header change in action

---

.github/actions/mint-token/action.yml

Change validated by new integration test against prod token minter

Use new header in mint-token action again

---

pkg/server/claims.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

Remove code for old version of auth header.

Deprecate old auth header

---

pkg/cli/private_key_import_cfg.go
pkg/cli/root.go
pkg/privatekey/config.go
pkg/server/token_minter_test.go

I planned to write private key import as a part of minty cli. The logic is not complete yet. Just add some function as the entrypoint.

feat: private key import

---

pkg/config/config_evaluator_test.go
pkg/config/config_loader_test.go
pkg/config/config_test.go
pkg/server/claims_test.go
pkg/server/jwk_resolver_test.go
pkg/server/permissions_test.go
pkg/server/token_minter_test.go

This is no longer required as of Go 1.22+

Remove shadowed loop variables

---

pkg/cli/private_key_import_cfg.go
pkg/privatekey/kms.go

part of https://github.com/abcxyz/github-token-minter/issues/170
This PR added the create cloud kms key function.

feat: created key function added

---

go.mod
pkg/cli/private_key_import_cfg.go
pkg/privatekey/config.go
pkg/privatekey/kms.go

part of https://github.com/abcxyz/github-token-minter/issues/170

feat: add importer job getOrCreate function

---

go.mod
go.sum
pkg/cli/private_key_import_cfg.go
pkg/privatekey/config.go
pkg/privatekey/kms.go

part of #170 
Added import key version function

feat: add import key version

---

pkg/cli/private_key_import_cfg.go

refactor: fixed docs

---

README.md
pkg/server/config.go
pkg/server/token_minter_test.go

chore: updated default value for org level config repo

---

docs/guides/MIGRATION_V2.md

Ran into this issue during migration, auth headers changed, forcing workflow step update.

Add note about updating workflows to migration doc

---

docs/guides/MIGRATION_V2.md

Additional clarification for config migration path.

Add tree diagram to v2 migration guide

---

.github/workflows/ci.yml
.github/workflows/create-tag.yml

Update to use the new actions repo for actions instead of pkg.

chore: use new actions repo

---

pkg/server/token_minter.go
pkg/server/token_minter_test.go

Minty allows requests for without permissions in the request object. This is uses the set of permissions defined at the scope level and replaces the empty set in the request with what is in the scope.
Unfortunately, when a request like this asks for a scope that specifies the special indicator "*", that says to use whatever the installed app allows, the request fails because it has replaced the request permissions (nil) with a value of {"*":"*"} which GitHub doesn't understand.
The fix is to catch this scenario, and set the request permissions to `nil` which indicates to GitHub to grant whatever permissions are defined on the app.
This PR comes with additional testing logic around this area to hopefully help catch future regressions as the logic here is a bit complicated.

fix: requests with no permissions against a scope that supports installed permissions instead of a fixed list fails
