abcxyz/github-token-minter

.github/actions/mint-token/action.yml
pkg/server/token_minter.go
pkg/server/token_minter_test.go

fix: handle 'created' response with invalid json returned by GitHub

---

abc.templates/deployments/spec.yaml
abc.templates/infra/spec.yaml

Previously rendered output,
```
deployments/
github-token-minter/
infra/
github-token-minter/
```
Proposed rendered output,
```
github-token-minter/
deployments/
infra/
```

chore: change target subdirectory defaults of abc-templates 

---

abc.templates/deployments/workflows/deploy-github-token-minter.yaml

This uses GitHub environments to display the status of the deployment on the repository homepage.

chore: add deployment environment to deployment workflow template

---

abc.templates/infra/contents/main.tf
abc.templates/infra/spec.yaml

Uses `custom_name` to override the default values of cloud run and log sink resource names. This also adds validation rules on the `custom_name` input variable.

chore: use custom name to customize cloud run resource names and log sink name

---

cmd/github-token-minter/main.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

Updated to lookup the proper GitHub App installation based on the organization name and the repository name instead of using the configuration value provided on the command line.

feat: multi-tenacy implementation

---

pkg/cli/mintycfg.go
pkg/cli/root.go
pkg/config/config_evaluator.go
pkg/config/config_evaluator_test.go
pkg/config/config_loader.go
pkg/config/config_loader_test.go
pkg/mintycfg/config.go
pkg/mintycfg/runner.go
pkg/server/config.go

Basic configuration file validation:
`go run cmd/minty/main.go config validate --minty-file=../secure-setup-terraform/.github/minty.yaml`
Will load the specified config file and compile all CEL expressions, it then outputs the configuration as it would be seen by minty like:
```
#################
Configuration and all rules compiled successfully
Config:
- Version: minty.abcxyz.dev/v2
- Rule.If: assertion.iss == 'https://token.actions.githubusercontent.com' &&
assertion.organization_id == '93787867' &&
assertion.repository_id == '560465650' &&
assertion.ref == 'refs/heads/main' 
- Scopes: 
- draft-release:
- Rule.If: assertion.workflow_ref == assertion.job_workflow_ref &&
assertion.workflow_ref.startsWith("abcxyz/secure-setup-terraform/.github/workflows/draft-release.yml") && …
```

feat: add configuration validation command

---

pkg/config/config_loader.go
pkg/config/config_loader_test.go

It should have fallen back to the org level loader but instead GitHub threw an error that wasn't handled well.

fix: in repo config loader failed when config file was not defined in local or the repository

---

pkg/cli/server.go
pkg/config/config_evaluator.go
pkg/config/config_evaluator_test.go
pkg/config/config_loader.go
pkg/config/config_loader_test.go
pkg/mintycfg/runner.go
pkg/server/config.go
pkg/server/runner.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

* Fixed a few configuration options that weren't being used
* Adjusted logging levels for startup configuration details
* Added additional logging in the config loaders to output the path to where the configuration is coming from e.g. `https://github.com/abcxyz/github-token-minter/.github/minty.yaml`. This will help when a scope doesn't resolve so we are sure its looking in the correct files.

feat: additional diagnostics to make debugging easier in prod

---

pkg/config/config.go
pkg/server/claims.go
pkg/server/token_minter_test.go

* Extract minty config GitHub repository from token's `aud` field

feat: support non-GitHub OIDC tokens

---

pkg/server/claims.go
pkg/server/config.go
pkg/server/jwk_resolver.go
pkg/server/jwk_resolver_test.go
pkg/server/runner.go
pkg/server/token_minter_test.go

* Dynamically resolve JWK key set used for token verification based on token's issuer URL and OpenID Configuration and cache key sets in the same way that we do in [JVS](https://github.com/abcxyz/jvs/blob/main/apis/v0/client.go#L36-L39). 
* Cache `jwks_uri` for issuers with a command line configured (default 4 hours) TTL (these should very rarely change) so we don't have to GET the OpenID Configs often. 
* Command line configured allowlist of issuers, defaulting to just GitHub and Google

feat: add verification for non-github oidc tokens

---

.github/minty.yaml

Previously I allowlisted the wrong service account. This is the one actually calling token minter from the CI integration flow, verified by logs.

Allow correct integration service account in minty cfg

---

.github/workflows/ci.yml

Sometimes changes to the mint-token action will work with the latest version of token minter but not with the version currently deployed to production, which causes issues. This test is to catch those cases.

Add integration test for mint-token action against production token minter

---

.github/actions/mint-token/action.yml
.github/workflows/ci.yml

Deprecated `mint-token` composite action in favor of moving the call to `auth` into the calling workflows.

feat: update CI process to call minty action as well as mint-token

---

terraform/main.tf
terraform/variables.tf

Adding a blanket passthrough so that users can set any additional environment variables that they may need rather than specifying the 8 possible existing environment variables separately. This will set us up for any future environment configuration to not require updates to the terraform module.

chore: add a passthrough for environment variables into the terraform module to the cloud run service

---

pkg/server/claims.go
terraform/github-wif.tf
terraform/variables.tf

This will allow us to deploy instances of minty for multiple organizations.

feat: Update WIF pool assertions to allow for enterprise id and/or organization id

---

pkg/cli/server.go

This is a short term fix to prevent the logging of the private key in a location that logs the configuration object.
Additional work to be done in https://github.com/abcxyz/github-token-minter/issues/201 to prevent this long term.

fix: remove logging of key

---

.github/minty.yaml

Moving the `create-tag` action to the abcyxz/actions repo changes the job_workflow_ref to be the actions repo instead of pkg. This causes the create-tag reusable workflow to fail when trying to lookup the correct scope for minty when trying to authenticate.

fix: minty config update for moving of create-tag action

---

go.mod
go.sum
pkg/cli/root.go
pkg/config/config_evaluator.go
pkg/config/config_loader.go
pkg/config/config_loader_test.go
pkg/server/config.go
pkg/server/runner.go
pkg/server/runner_test.go
pkg/server/source/github.go
pkg/server/source/source_system.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

* Moved the GitHub specific code behind an interface to make room for additional implementations (GitLab).
* Started a means to specify multiple GitHub Apps to be used. 
The multi App work is not completed as there are two things left to solve in a follow up PR that I wouldn't mind some feedback on. The current implementation just loops through them which is dumb.
* First, how to deal with configuration for multiple Apps. I'm not sure if I want multiple command line options as they would need to be pairs of APP_ID/PRIVATE_KEY so possibly some kind of config file is warranted? This needs to be thought through still.
* Second, how to determine which app to pick for any given request. I'm thinking this is probably tied to the request object but I'm still trying to figure out how to do this …

feat: extracted GitHub specific code into an isolated class

---

pkg/cli/server.go
pkg/server/config.go

Fixes #201 
This will prevent accidental of logging of private keys if the config object gets logged.

feat: implement slog/LogValuer to redact private keys no matter where they are logged

---

pkg/config/config_loader_test.go
pkg/server/source/github.go

Fixes #205 
Attempts to mint a token for a nonexistent repository were causing hard failures instead of being handled correctly. In this scenario the correct thing to do is to treat it as if the file is not found and continue processing up the tree looking for other files that might contain the requested scope.

fix: treat a missing org level repo as a 'not found' scenario instead of a hard failure

---

.github/workflows/ci.yml
pkg/config/config_evaluator_test.go
pkg/server/runner.go
terraform/main.tf

This secret was a left over from earlier < 1.0 deployments where we targeted a specific installation. This secret is no longer used and doesn't need to be created.

chore: remove GITHUB_INSTALL_ID from the terraform module as it hasn't been needed since v2.0

---

pkg/server/token_minter.go
pkg/server/token_minter_test.go

This change ensures that token requests with an unspecified or empty list of repositories default to the repository contained in the OIDC token claim. 
This change introduces logic at the beginning of the processRequest function to inspect the incoming tokenRequest.
- If the Repositories slice in the request is empty (either because the key was omitted or an empty array [] was provided), the slice is explicitly populated with the repository name parsed from the OIDC token's repository claim.
- This does not impact requests for '*' which has special case logic to retrieve the repositories list from the configuration file.
This change ensures that, by default, the scope of the minted token is narrowed to only the repository that initiated the request.
** Verification **
To ensure the fix is …

feat: explicitly default to the repository in the OIDC token if no repository is specified in the request object.

---

pkg/privatekey/config.go
pkg/server/token_minter.go
pkg/server/token_minter_test.go

Adding * to request/allowed access list caused empty [] comparison to no longer be treated as an action that worked on org level resources

fix: org level tokens no longer functioned without new * syntax
